spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.106.44:3306/admin?serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: interview
    password: 123456
  redis:
    #数据库索引
    database: 4
    host: 49.234.106.44
    port: 6380
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000

logging:
  level:
    com:
      example:
        security:
          mapper: debug
  config: classpath:logback.xml
